name = "gemini-balance-lite"
# 主入口
main = "src/index.js"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]


# #
[vars]
GEMINI_API_KEYS = "${GEMINI_API_KEYS}"

[[kv_namespaces]]
binding = "GEMINI_BALANCE_LITE_KV"
id = "4b40be1d35ad496fad70c15c88962e8d"
preview_id = "4b40be1d35ad496fad70c15c88962e8d"